### ISSUE TITLE
DiscordAPIError: Invalid Form Body content: Must be 2000 or fewer in length.

### ISSUE THREAD

**Issue by anlexmatos** [ava-cassiopeia/discord-text-adventure-bot#53]
Zork Zero crashes the bot at move 6 with the following console output:

```
discord-frotz\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (C:\msys64\home\exander\Development\frotzbot\node-v16.13.0-win-x64\node_modules\discord-frotz\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\msys64\home\exander\Development\frotzbot\node-v16.13.0-win-x64\node_modules\discord-frotz\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/910621836138676234/messages',
  code: 50035,
  httpStatus: 400
}

```

**Comment by ava-cassiopeia** [comment]
Ah this seems to be a case in which the bot is running up against the discord character limit for a single message. The obvious solution is to just split up messages that are too large, but that does potentially make formatting tricky. I'll look into this a little more when I can.
